# frozen_string_literal: true

module Discovery
  module Sources
    module WaSos
      module BusinessTypes
        DEFAULT_ID = "65"

        OPTIONS = [
          ["FOREIGN BANK CORPORATION", "14"],
          ["FOREIGN BANK LIMITED LIABILITY COMPANY", "15"],
          ["FOREIGN COOPERATIVE ASSOCIATION", "16"],
          ["FOREIGN CREDIT UNION", "17"],
          ["FOREIGN INSURANCE COMPANY", "19"],
          ["FOREIGN LIMITED LIABILITY COMPANY", "20"],
          ["FOREIGN LIMITED LIABILITY LIMITED PARTNERSHIP", "21"],
          ["FOREIGN LIMITED LIABILITY PARTNERSHIP", "22"],
          ["FOREIGN LIMITED PARTNERSHIP", "23"],
          ["FOREIGN MASSACHUSETTS TRUST", "24"],
          ["FOREIGN NAME REGISTRATION", "25"],
          ["FOREIGN NONPROFIT CORPORATION", "26"],
          ["FOREIGN NONPROFIT PROFESSIONAL SERVICE CORPORATION", "27"],
          ["FOREIGN PROFESSIONAL LIMITED LIABILITY COMPANY", "33"],
          ["FOREIGN PROFESSIONAL LIMITED LIABILITY PARTNERSHIP", "35"],
          ["FOREIGN PROFESSIONAL SERVICE CORPORATION", "37"],
          ["FOREIGN PROFIT CORPORATION", "38"],
          ["FOREIGN PUBLIC UTILITY CORPORATION", "39"],
          ["FOREIGN SAVINGS AND LOAN ASSOCIATION", "40"],
          ["JOINT MUNICIPAL UTILITY SERVICE", "43"],
          ["MILITARY CORPORATION", "44"],
          ["WA ASSOCIATION UNDER FISH MARKETING ACT", "54"],
          ["WA BANK CORPORATION", "55"],
          ["WA BANK LIMITED LIABILITY COMPANY", "56"],
          ["WA BUILDING SOCIETY COMPOSED OF FRATERNAL MEMBERS", "57"],
          ["WA COOPERATIVE ASSOCIATION", "58"],
          ["WA CORP SOLE", "59"],
          ["WA CREDIT UNION", "60"],
          ["WA EMPLOYEE COOPERATIVE", "61"],
          ["WA FRATERNAL SOCIETY", "62"],
          ["WA GRANGE", "63"],
          ["WA INSURANCE COMPANY", "64"],
          ["WA LIMITED LIABILITY COMPANY", "65"],
          ["WA LIMITED LIABILITY LIMITED PARTNERSHIP", "67"],
          ["WA LIMITED LIABILITY PARTNERSHIP", "68"],
          ["WA LIMITED PARTNERSHIP", "69"],
          ["WA MASSACHUSETTS TRUST", "71"],
          ["WA MISCELLANEOUS AND MUTUAL CORPORATION", "72"],
          ["WA NONPROFIT CORPORATION", "73"],
          ["WA NONPROFIT PROFESSIONAL SERVICE CORPORATION", "74"],
          ["WA PROFESSIONAL LIMITED LIABILITY COMPANY", "79"],
          ["WA PROFESSIONAL LIMITED LIABILITY PARTNERSHIP", "76"],
          ["WA PROFESSIONAL SERVICE CORPORATION", "85"],
          ["WA PROFIT CORPORATION", "86"],
          ["WA PUBLIC UTILITY CORPORATION", "88"],
          ["WA SAVINGS AND LOAN ASSOCIATION", "89"],
          ["WA SOCIAL PURPOSE CORPORATION", "90"]
        ].freeze
      end
    end
  end
end
